spring.application.name=productservice
server.port=9099

spring.datasource.url=jdbc:oracle:thin:@employeedemo_medium?TNS_ADMIN=/opt/oracle/wallet
spring.datasource.username=PRODUCT_APP
spring.datasource.password=SharmilaRam#26
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

couponService.url=http://couponservice:9098/couponapi/coupons/